In [3]:
import numpy as np
import pandas as pd

df=pd.DataFrame({'X': [7,2,0,3,4,2,5,0,3,4]})

idx=df.index[df['X']].tolist()

to_zero=[(idx[i::-1]+[0]).index(0) for i in range (len(idx))]

df['Y']=np.random.randint(0,5, size= len(df))

display(df)

display(to_zero)

   X  Y
0  7  1
1  2  3
2  0  3
3  3  4
4  4  2
5  2  2
6  5  3
7  0  0
8  3  0
9  4  1

[1, 2, 0, 1, 2, 3, 4, 0, 1, 2]

In [21]:
import numpy as np
import pandas as pd
import calendar

rng = pd.date_range('1/1/2015', periods=365, freq='D')

ts = pd.Series(np.random.randn(len(rng)), index=rng)

print(ts)

2015-01-01   -0.380228
2015-01-02    0.981599
2015-01-03    0.628512
2015-01-04    0.763691
2015-01-05    0.976508
2015-01-06    0.152324
2015-01-07    0.204558
2015-01-08    0.103908
2015-01-09   -2.056472
2015-01-10    1.966108
2015-01-11    0.908035
2015-01-12   -1.016806
2015-01-13    0.070273
2015-01-14   -0.264302
2015-01-15    2.125860
2015-01-16    0.754480
2015-01-17    1.139994
2015-01-18   -1.616384
2015-01-19    0.036826
2015-01-20   -0.734262
2015-01-21   -0.697070
2015-01-22   -0.366783
2015-01-23   -0.312591
2015-01-24    0.700067
2015-01-25   -0.051200
2015-01-26    0.277120
2015-01-27   -0.931531
2015-01-28   -1.552026
2015-01-29   -0.394842
2015-01-30   -0.071747
                ...
2015-12-02   -0.313093
2015-12-03   -1.551323
2015-12-04    1.836940
2015-12-05    2.470129
2015-12-06   -1.624423
2015-12-07   -0.739472
2015-12-08   -0.298089
2015-12-09   -0.141834
2015-12-10   -1.789306
2015-12-11   -1.401925
2015-12-12   -0.545312
2015-12-13   -0.293416
2015-12-14   -0.705508
2015-12-15   -1.444776
2015-12-16   -0.760213
2015-12-17    1.356390
2015-12-18   -1.399825
2015-12-19    0.662044
2015-12-20   -1.108641
2015-12-21    0.461363
2015-12-22   -0.148360
2015-12-23   -1.494160
2015-12-24    0.610800
2015-12-25   -1.232164
2015-12-26    2.207258
2015-12-27   -0.635948
2015-12-28   -0.728628
2015-12-29   -1.001134
2015-12-30    1.137153
2015-12-31    1.076582
Freq: D, Length: 365, dtype: float64